language: java
cache:
  directories:
    - $HOME/.m2
#
#  Travis default commands are pretty dumb
#  - install is supposed to be the equivalent of "npm install", i.e download dependencies.
#    However, their default command for this does an "mvn install", which as they say themselves in their doc, is much
#    more than that.
#    Was hoping to do a mvn dependency:resolve, but it fails on dependencies from the reactor.
#    Skip it entirely, it's not like we changing dependencies every day.
#
#  - script is the thing that actually builds. Since we have caching, we don't actually want to install our built
#    jars; we just do a 'verify'.
#
install: echo Skip me > /dev/null
script: ./mvnw clean verify -B -V
