packages:
  - packages/**
allowBuilds:
  esbuild: false
catalog:
  "@chromatic-com/storybook": 5.2.1
  "@emotion/react": 11.14.0
  "@emotion/styled": 11.14.1
  "@eslint/eslintrc": 3.3.5
  "@eslint/js": 10.0.1
  "@inquirer/prompts": ^8.5.2
  "@mui/icons-material": 9.1.1
  "@mui/material": 9.1.1
  "@prettier/plugin-xml": 3.4.2
  "@storybook/addon-docs": 10.4.3
  "@storybook/addon-links": 10.4.3
  "@storybook/react": 10.4.3
  "@storybook/react-vite": 10.4.3
  "@testing-library/jest-dom": 6.9.1
  "@testing-library/react": 16.3.2
  "@testing-library/user-event": 14.6.1
  "@toolpad/core": 0.16.0
  "@types/fs-extra": 11.0.4
  "@types/node": 24.13.2
  "@types/react": 19.2.17
  "@types/react-dom": 19.2.3
  "@types/ws": 8.18.1
  "@vitejs/plugin-react": 6.0.2
  commander: 15.0.0
  eslint: 10.4.1
  eslint-config-prettier: 10.1.8
  eslint-plugin-prettier: 5.5.6
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 7.1.1
  eslint-plugin-storybook: 10.4.4
  fs-extra: 11.3.5
  husky: 9.1.7
  inquirer: 14.0.2
  jsdom: 29.1.1
  kleur: 4.1.5
  nanoid: 5.1.11
  prettier: 3.8.4
  prettier-plugin-java: 2.9.7
  pretty-quick: 4.2.2
  react: 19.2.7
  react-dom: 19.2.7
  storybook: 10.4.3
  ts-enum-util: 4.1.0
  tslib: 2.8.1
  typedoc: 0.28.19
  typescript: 6.0.3
  typescript-eslint: 8.61.0
  vite: 8.0.16
  vite-plugin-eslint: 1.8.1
  vite-plugin-svgr: 5.2.0
  vitest: 4.1.8
  ws: 8.21.0

cleanupUnusedCatalogs: true
