name: Tichu main build

on:
  push:
    branches: [master, reuse-github-workflow-in-frontend-setup]
  pull_request:
    # By default, a workflow only runs when a pull_request's activity type is opened, synchronize, or reopened
    # With types: [opened], we only run on open, so further pushes do not re-trigger, to avoid completely overloading CI
    # types: [opened]
    # Unfortunately, manual triggers do not propagate to PR checks :|
    # TODO: alternatively, we could branches-ignore: [renovate/**] but that would need to be on the push event?
    branches: [master]
  # Enable manual triggers:
  workflow_dispatch:

jobs:
  build-backend:
    name: Backend w/ Java ${{ matrix.java-version }} ${{ matrix.java-distrib }} ${{ matrix.experimental && '🧪' || '📍' }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }} # if experimental, don't fail the whole job
    strategy:
      fail-fast: true # cancel other jobs if one in matrix fails
      matrix:
        # the first item in the versions list exists only to match .tool-versions
        java-version: ["21.0.5+11.0.LTS", "21", "23"]
        java-distrib: ["temurin"]
        experimental: [false]
        include:
          # graalvm doesn't have 23 yet?
          - java-version: 21
            java-distrib: graalvm
            experimental: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        name: Set up Java environment
        with:
          java-version: "${{ matrix.java-version }}"
          distribution: "${{ matrix.java-distrib }}"
          cache: "maven"
      - name: Backend Build
        run: ./mvnw clean verify -B -V
  build-clients:
    name: Build Clients/Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tichu-clients
        # Some of the commands below need this shell setup -- https://github.com/actions/virtual-environments/issues/4#issuecomment-600025775
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/frontend-setup
      - name: Frontend Build
        run: npm run build
      - name: Frontend Prettier Check
        run: npm run prettier-check-all

  # Because there may be bugs hiding here (and testing stories isn't something I'll do today)
  build-storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tichu-clients
        # Some of the commands below need this shell setup -- https://github.com/actions/virtual-environments/issues/4#issuecomment-600025775
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/frontend-setup
      - name: Storybook Build
        run: npm run web-build-storybook
