name: Update node and npm versions

on:
  workflow_dispatch:
    inputs:
      nodeVersion:
        description: Node version
        required: false
      npmVersion:
        description: NPM version
        required: false

jobs:
  update-node-npm:
    name: "Update node to version ${{ inputs.nodeVersion }} and npm to version ${{ inputs.npmVersion }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Mise en place
        uses: jdx/mise-action@v4
      - name: Update node and npm versions in repo
        id: apply-update
        run: tichu-clients/update-node-npm.sh ${{ inputs.nodeVersion }} ${{ inputs.npmVersion }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        id: create-pr
        with:
          token: ${{ secrets.GREG_GITBOT_TOKEN }}
          commit-message: "Updating node to ${{ steps.apply-update.outputs.nodeVersion }} and npm to ${{ steps.apply-update.outputs.npmVersion }}"
          title: "Updating node to ${{ steps.apply-update.outputs.nodeVersion }} and npm to ${{ steps.apply-update.outputs.npmVersion }}"
          branch: update-node-npm
      - name: Print PR details
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        run: |
          echo "Pull request     - #${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
      - name: Enable PR automerge
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        run: gh pr merge --merge --auto "${{ steps.create-pr.outputs.pull-request-number }}"
