name: Update node and npm versions

on:
  workflow_dispatch:
    inputs:
      nodeVersion:
        description: Node version
        required: false
      npmVersion:
        description: NPM version
        required: false

jobs:
  update-node-npm:
    name: "Update node to version ${{ inputs.nodeVersion }} and npm to version ${{ inputs.npmVersion }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Mise en place
        uses: jdx/mise-action@v4
      - name: Install fd
        # because I can't set it up in mise.toml while it doesn't work on my old intel mac
        run: mise use fd
      - name: Update node and npm versions in repo
        run: tichu-clients/update-node-npm.sh ${{ inputs.nodeVersion }} ${{ inputs.npmVersion }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        id: pr
        with:
          token: ${{ secrets.GREG_GITBOT_TOKEN }}
          commit-message: "Updating node to ${{ inputs.nodeVersion }} and npm to ${{ inputs.npmVersion }}"
          title: "Updating node to ${{ inputs.nodeVersion }} and npm to ${{ inputs.npmVersion }}"
          branch: update-node-npm
      - name: Print PR details
        if: ${{ steps.pr.outputs.pull-request-number }}
        run: |
          echo "Pull request     - #${{ steps.pr.outputs.pull-request-number }}"
          echo "Pull request URL - ${{ steps.pr.outputs.pull-request-url }}"

#      - name: Enable PR automerge Request Automerge
#        if: ${{ steps.pr.outputs.pull-request-number }}
#        run: gh pr merge --merge --auto "${{ steps.pr.outputs.pull-request-number }}"
