name: Update node and npm versions

on:
  workflow_dispatch:
    inputs:
      nodeVersion:
        description: Node version
        required: true
      npmVersion:
        description: NPM version
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-node-npm:
    name: Update node and npm versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update node and npm versions in repo
        run: tichu-clients/update-node-npm.sh ${{ inputs.nodeVersion }} ${{ inputs.npmVersion }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: pr
        with:
          commit-message: "Updating node to ${{ inputs.nodeVersion }} and npm to ${{ inputs.npmVersion }}"
          title: "Updating node to ${{ inputs.nodeVersion }} and npm to ${{ inputs.npmVersion }}"
          branch: update-node-npm
      - name: Print PR details
        if: ${{ steps.pr.outputs.pull-request-number }}
        run: |
          echo "Pull request nr  - ${{ steps.pr.outputs.pull-request-number }}"
          echo "Pull request URL - ${{ steps.pr.outputs.pull-request-url }}"

#      - name: Enable PR automerge Request Automerge
#        if: ${{ steps.pr.outputs.pull-request-number }}
#        run: gh pr merge --merge --auto "${{ steps.pr.outputs.pull-request-number }}"
